from __future__ import annotations

import base64
from pathlib import Path
from urllib.parse import quote

from vsf_profiler.csv_catalog import CsvCatalog
from vsf_profiler.models import ColumnSchema, Schema, TableSchema


MAX_DBML_LINK_CHARS = 16_000


def build_schema_diagram(schema: Schema, catalog: CsvCatalog, out_dir: Path) -> dict:
    dbml = render_dbml_for_diagram(schema, catalog)
    dbml_path = out_dir / "schema_diagram.dbml"
    dbml_path.write_text(dbml)

    encoded = quote(base64.b64encode(dbml.encode("utf-8")).decode("ascii"), safe="")
    dbdiagram_url = f"https://dbdiagram.io/embed?c={encoded}"
    if len(dbdiagram_url) > MAX_DBML_LINK_CHARS:
        dbdiagram_url = ""

    diagram = {
        "dbml_path": dbml_path.name,
        "dbdiagram_url": dbdiagram_url,
        "dbdiagram_url_available": bool(dbdiagram_url),
        "dbdiagram_note": (
            "Open this stateless dbdiagram.io link to view the DBML ER diagram."
            if dbdiagram_url
            else "DBML is too large for a safe dbdiagram.io URL; use schema_diagram.dbml instead."
        ),
        "tables": [_table_mapping(table_name, table_schema, catalog) for table_name, table_schema in schema.tables.items()],
        "relationships": [rel.model_dump() for rel in schema.relationships],
        "extra_csvs": [
            {"table": stem, "csv_path": f"{stem}.csv", "status": "extra_csv"}
            for stem in catalog.extra_csvs
        ],
    }
    return diagram


def render_dbml_for_diagram(schema: Schema, catalog: CsvCatalog) -> str:
    blocks: list[str] = [
        "// Generated by VSF Data Profiler.",
        "// The CSV mapping is also written to schema_diagram.json and the report.",
        "",
    ]
    for table_name, table_schema in schema.tables.items():
        catalog_table = catalog.tables.get(table_name)
        csv_note = f"CSV: {_source_label(catalog_table)}" if catalog_table else "CSV: missing"
        blocks.append(f"Table {table_name} {{")
        blocks.append(f"  Note: '{_escape_dbml_note(csv_note)}'")
        for column in table_schema.columns.values():
            blocks.append(f"  {_render_column(column)}")
        if len(table_schema.primary_key) > 1:
            pk = ", ".join(table_schema.primary_key)
            blocks.extend(["", "  indexes {", f"    ({pk}) [pk]", "  }"])
        blocks.append("}")
        blocks.append("")
    return "\n".join(blocks).rstrip() + "\n"


def _render_column(column: ColumnSchema) -> str:
    attrs: list[str] = []
    if column.is_pk:
        attrs.append("pk")
    if column.not_null:
        attrs.append("not null")
    if column.unique:
        attrs.append("unique")
    if column.foreign_key:
        attrs.append(f"ref: > {column.foreign_key.parent_table}.{column.foreign_key.parent_column}")
    suffix = f" [{', '.join(attrs)}]" if attrs else ""
    return f"{column.name} {column.type}{suffix}"


def _table_mapping(table_name: str, table_schema: TableSchema, catalog: CsvCatalog) -> dict:
    catalog_table = catalog.tables.get(table_name)
    relationships = []
    for column in table_schema.columns.values():
        if column.foreign_key:
            relationships.append(
                {
                    "column": column.name,
                    "parent_table": column.foreign_key.parent_table,
                    "parent_column": column.foreign_key.parent_column,
                }
            )
    return {
        "table": table_name,
        "csv_path": _source_label(catalog_table) if catalog_table else "",
        "status": "mapped" if catalog_table else "missing_csv",
        "primary_key": table_schema.primary_key,
        "foreign_keys": relationships,
        "column_count": len(table_schema.columns),
    }


def _escape_dbml_note(value: str) -> str:
    return value.replace("\\", "\\\\").replace("'", "\\'")


def _source_label(catalog_table) -> str:
    if catalog_table is None:
        return ""
    return catalog_table.source_name or str(catalog_table.csv_path)
